language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r requirements/dev.txt"
  - "pip install -r requirements/compiled.txt"
  - "pip install rednose coverage coveralls"

script:
  - PYTHONPATH=vendor/lib/python nosetests -v --rednose --force-color auslib/test
  - coverage run -a scripts/test-rules.py -v
  - pyflakes $(find . \( -iname "*.py" -or -iname "*.wsgi" \) -not -path "*vendor*")

after_success:
  - coveralls --rcfile coveragerc

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# please comment out this section in your personal fork!
notifications:
  irc:
    channels:
      - "irc.mozilla.org#callek"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
