---
  title: "Settings Blob"
  type: "object"
  required: 
    - "name"
    - "schema_version"
    - "settings"
  additionalProperties: false
  properties: 
    name: 
      type: "string"
      description: "Human readable identifier"
      minLength: 1
      maxLength: 100
    schema_version: 
      type: "number"
      description: "Blob identifier number"
      enum: 
        - 2000
    settings: 
      type: "object"
      properties: 
        settingName: 
          type: "object"
          required: 
            - "version"
            - "last_modified"
          additionalProperties: false
          properties: 
            version: 
              type: "string"
              description: "Version id of the setting"
            last_modified: 
              type: "number"
              description: "Last modified timestamp of the setting"

